import json

from .utils import get_last_message, log, log_block, log_done, log_node, truncate
from e2b_code_interpreter import Sandbox

SUCCESS = "Code ran successfully"
NO_CODE = "Code not generated yet, Write a code first."

# Seconds AppTest may spend on a single script run inside the sandbox
APPTEST_TIMEOUT = 60
# Marker prefix so the verdict can be picked out of stdout, which is also full of
# Streamlit's own warnings and anything the generated app prints
VERDICT = "__APPTEST_VERDICT__"


def _apptest_harness(py_code):
    """
    Build the snippet that actually exercises the app inside the sandbox.

    Running a Streamlit script as plain Python (which is what sbx.run_code does) gives
    it no ScriptRunContext, so Streamlit falls back to "bare mode": every st.* call
    becomes a no-op and the widget-ID registry never runs. Whole classes of real bugs
    — duplicate auto-generated element IDs, bad widget arguments, errors inside a
    callback — therefore exit 0 and get reported as working code.

    AppTest runs the script in a genuine script-run context, so those surface as real
    exceptions. The app source is embedded with repr() and written out inside the
    sandbox, which avoids depending on the sandbox file-transfer API.
    """
    # Written with dict(...) rather than brace literals so the f-string needs no escaping
    return f'''
import json, pathlib, traceback

# Absolute: AppTest.from_file resolves a relative path against the file that calls
# it, which in a Jupyter kernel is /tmp/ipykernel_*/, not the directory we wrote to.
APP = str(pathlib.Path("app_under_test.py").resolve())
pathlib.Path(APP).write_text({py_code!r}, encoding="utf-8")

def _verdict(payload):
    print("{VERDICT}" + json.dumps(payload))

def _err(exc_type, message, tb=""):
    _verdict(dict(status="error", type=exc_type, message=message, traceback=tb))

def main():
    # Streamlit's script runner swallows compilation errors: it logs them itself and
    # leaves at.exception empty without run() raising, so a syntax error would
    # otherwise be reported as a clean run. Compile explicitly first.
    try:
        compile(pathlib.Path(APP).read_text(encoding="utf-8"), APP, "exec")
    except SyntaxError as exc:
        return _err("SyntaxError", str(exc), traceback.format_exc())

    try:
        from streamlit.testing.v1 import AppTest
    except Exception as exc:
        return _verdict(dict(status="no_streamlit", message=str(exc)))

    try:
        at = AppTest.from_file(APP, default_timeout={APPTEST_TIMEOUT})
        at.run()
    except Exception as exc:
        return _err(type(exc).__name__, str(exc), traceback.format_exc())

    if at.exception:
        ex = at.exception[0]
        return _err(str(getattr(ex.proto, "type", "Exception")),
                    str(ex.message), "".join(ex.stack_trace or []))
    _verdict(dict(status="ok"))

main()
'''


def _read_verdict(execution):
    """Pull the JSON verdict line out of the sandbox's stdout, or None if absent."""
    for line in (execution.logs.stdout or []):
        for part in str(line).splitlines():
            if part.startswith(VERDICT):
                try:
                    return json.loads(part[len(VERDICT):])
                except json.JSONDecodeError:
                    return None
    return None


def code_interpreter():
    """
    Runs the code generated by the programmer in a sandbox.

    Returns SUCCESS, NO_CODE, or a message describing the failure. The three cases
    are kept distinct on purpose: the router sends anything that is not SUCCESS back
    to the Programmer to be fixed, so reporting an infrastructure failure (missing
    E2B_API_KEY, sandbox timeout, network error) as a code error makes the programmer
    rewrite working code to chase a problem that is not in the code.
    """
    code_solution = get_last_message()
    if code_solution is None:
        # Nothing in the database yet — the programmer has not produced code
        log("  nothing in the database yet - no code to run")
        return NO_CODE

    install_code = code_solution['install']
    py_code = code_solution['imports'] + "\n\n" + code_solution['code']

    try:
        # Context manager kills the sandbox on every exit path, including exceptions.
        # By default the sandbox is alive for 5 minutes.
        log("  starting e2b sandbox")
        with Sandbox() as sbx:
            log(f"  installing dependencies: {install_code}")
            try:
                sbx.commands.run(install_code)
            except Exception as e:
                log(f"  dependency install FAILED: {e}")
                return "Error occurred while installing dependencies: " + str(e)

            log(f"  running app under AppTest ({len(py_code.splitlines())} lines)")
            result_code = sbx.run_code(_apptest_harness(py_code))

            # The harness itself failed to run — treat as a plain execution error
            if result_code.error is not None:
                code_error = result_code.error
                log(f"  harness crashed: {code_error.name}: {code_error.value}")
                return ("Error occurred: " + code_error.name + " " + code_error.value
                        + "\ntraceback: " + code_error.traceback)

            verdict = _read_verdict(result_code)

            if verdict is None:
                log("  no verdict returned - run was cut short")
                # No verdict line: the run was cut short (sandbox timeout, killed
                # process). Not a defect in the generated code.
                return ("Sandbox failure: the app check produced no verdict, so the "
                        "run did not complete. This is an environment problem, not an "
                        "error in the generated code.")

            if verdict["status"] == "ok":
                log("  VERDICT: app ran clean")
                return SUCCESS

            if verdict["status"] == "no_streamlit":
                # Actionable by the programmer: its install section is incomplete
                log("  VERDICT: streamlit missing from the sandbox")
                return ("Error occurred: streamlit is not importable in the sandbox ("
                        + verdict["message"] + "). Add streamlit to the install section.")

            log(f"  VERDICT: {verdict.get('type', 'Exception')}")
            log_block("error", verdict.get("message", ""))
            log_block("traceback", verdict.get("traceback", ""))
            return ("Error occurred: " + verdict.get("type", "Exception") + " "
                    + verdict.get("message", "")
                    + "\ntraceback: " + verdict.get("traceback", ""))
    except Exception as e:
        # Sandbox could not be created or died mid-run: an infrastructure problem,
        # not a defect in the generated code. Log the real exception rather than
        # discarding it behind a generic message.
        log(f"  SANDBOX FAILURE: {type(e).__name__}: {e}")
        print(f"Sandbox failure: {type(e).__name__}: {e}")
        return (f"Sandbox failure ({type(e).__name__}): {e}. "
                "This is an environment problem, not an error in the generated code. "
                "Check that E2B_API_KEY is set and the e2b service is reachable.")


def code_interpreter_agent(state):
    """
    Check code

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, error
    """

    print("\n\n---CODE INTERPRETER WORKING---")
    log_node("CODE INTERPRETER", state["iterations"])

    # State
    code_interpreter_output = code_interpreter()
    if code_interpreter_output != SUCCESS:
        # code_interpreter() logs the detail; keep a one-line record of the outcome too
        log(f"  result: {truncate(code_interpreter_output, 300)}")
    log_done("clean" if code_interpreter_output == SUCCESS else "failed")

    state["messages"] += [
        (
            "code_interpreter",
            (
                "assistant",
                f"{code_interpreter_output}",
            ))
    ]

    state['generation'] = code_interpreter_output
    state['sender'] = 'code_interpreter'

    return state